apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-configmaps-glob
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/davidseve/delete.git # Cambia por tu repositorio
        revision: HEAD
        directories:
          - path: applicationsGlob/*
  template:
    metadata:
      name: '{{ .path.basename }}-glob'
    spec:
      project: default
      sources:
        # Source 1: El chart compartido
        - repoURL: https://github.com/davidseve/delete.git  # Cambia por tu repositorio
          targetRevision: HEAD
          path: test
          helm:
            valueFiles:
              - $values/{{ .path.path }}/values.yaml
              - $values/{{ .path.path }}/configmaps/**/*.yaml
        # Source 2: Referencia para los values
        - repoURL: https://github.com/davidseve/delete.git  # Cambia por tu repositorio
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

