apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-configmaps-values
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/davidseve/delete.git # Cambia por tu repositorio
        revision: HEAD
        directories:
          - path: applications/*
  template:
    metadata:
      name: '{{ .path.basename }}-values'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/davidseve/delete.git 
          targetRevision: HEAD
          path: test
          helm:
            valueFiles:
              - $values/{{ .path.path }}/values.yaml
        - repoURL: https://github.com/davidseve/delete.git 
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true


